# Generated by Django 3.1.7 on 2021-03-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('hr_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.hrperson')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hr_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.hrperson')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hr_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.hrperson')),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_link', models.CharField(max_length=1000)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='boards.person')),
            ],
        ),
        migrations.CreateModel(
            name='SupportPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.supportteam')),
            ],
            bases=('boards.person',),
        ),
        migrations.CreateModel(
            name='CorporatePerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.corporateteam')),
            ],
            bases=('boards.person',),
        ),
    ]
