# Generated by Django 3.1.7 on 2021-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_birthdayevent_corporateperson_corporateteam_person_supportperson_supportteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=12345678),
        ),
    ]
