# Generated by Django 3.1.7 on 2021-03-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210313_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hr_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.hrperson')),
            ],
        ),
        migrations.RemoveField(
            model_name='corporateteam',
            name='hr_person',
        ),
        migrations.RemoveField(
            model_name='supportperson',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='supportperson',
            name='team',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='hr_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hr_person',
        ),
        migrations.DeleteModel(
            name='CorporatePerson',
        ),
        migrations.DeleteModel(
            name='CorporateTeam',
        ),
        migrations.DeleteModel(
            name='SupportPerson',
        ),
        migrations.DeleteModel(
            name='SupportTeam',
        ),
    ]
