# Generated by Django 3.1.7 on 2021-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_person_is_support_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayevent',
            name='date',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
