# Generated by Django 3.1.7 on 2021-03-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210314_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayevent',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.person'),
        ),
    ]
