# Generated by Django 3.1.7 on 2021-03-16 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210316_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayevent',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 15, 19, 32, 285012)),
        ),
    ]
