# Generated by Django 3.1.7 on 2021-03-16 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_birthdayevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
